In [41]:
pip install streamlit pandas numpy plotly matplotlib seaborn openpyxl

Requirement already satisfied: streamlit in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (1.58.0)
Requirement already satisfied: pandas in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (3.0.0)
Requirement already satisfied: numpy in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (2.4.1)
Requirement already satisfied: plotly in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (6.7.0)
Requirement already satisfied: matplotlib in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: openpyxl in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (7.1.4)
Requirement already satisfied: click<9,>=7.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: packaging>=20 in c:\users\jayshri\appdata\roaming\python\python311\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (12.1.1)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (7.34.1)
Requirement already satisfied: pyarrow>=7.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\jayshri\appdata\roaming\python\python311\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.50.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.14.1)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jayshri\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from plotly) (2.20.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pyparsing>=3 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: et-xmlfile in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: jinja2 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: idna>=2.8 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from anyio>=4.0.0->streamlit) (3.10)
Requirement already satisfied: colorama in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: six>=1.5 in c:\users\jayshri\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2024.12.14)
Requirement already satisfied: h11>=0.8 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\jayshri\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
import pandas as pd 
import numpy as np 
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv("netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.9 MB

In [45]:
df['director'] = df['director'].fillna('unknown director')
df['cast'] = df['cast'].fillna('unknown cast')
df['country'] = df['country'].fillna('unknown country')

In [46]:
df = df.dropna(subset=['date_added', 'rating', 'duration'])

In [47]:

df['date_added'] = df['date_added'].astype(str).str.strip()
df['date_added'] = pd.to_datetime(df['date_added'])
df['date_added'] = df['date_added'].dt.strftime('%d-%m-%Y')

In [48]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown cast,United States,25-09-2021,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,unknown director,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-09-2021,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown country,24-09-2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,unknown director,unknown cast,unknown country,24-09-2021,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,unknown director,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-09-2021,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,20-11-2019,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,unknown director,unknown cast,unknown country,01-07-2019,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,01-11-2019,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,11-01-2020,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,02-03-2019,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...